management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=shutdown

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s

spring.datasource.url=jdbc:postgresql://localhost:5432/switchcore
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=capb.caio.becker@gmail.com
spring.mail.password=D@SENHA_DE_APP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true